language: node_js
node_js: node
services: postgresql
env:
- NODE_ENV=test
before_script:
- npm install -g gulp-cli
- gulp compile
- npm run create-database
- npm run create-schema
- npm run create-mock-data
after_script:
- npm run drop-all
branches:
  only:
  - HuuVinh-f-Angular2
  - DucThanh-Angular2
  - nha-f-notifi
notifications:
  slack: nodejsapisecurity:sz840dPqzq2zgUnjlkSA9BRe